### ISSUE TITLE
Checkpoint of CoN-CLIP

### ISSUE THREAD

**Issue by wysoczanska** [jaisidhsingh/CoN-CLIP#1]
Hi, thanks for your work!
Are you planning to share the checkpoints of CoN-CLIPs? I'd very much appreciate it.

**Comment by Code-kunkun** [comment]
+1

**Comment by jaisidhsingh** [comment]
Hi everyone. The README has been updated with links to the checkpoints (L-14, B-32, and B-16). These are hosted on OneDrive for which I am adding a link to a command line tool for easier usage. Thank you for your interest in our work!

**Comment by jaisidhsingh** [comment]
Closing this issue.
