### ISSUE TITLE
Hosting checkpoints on other platform

### ISSUE THREAD

**Issue by ytaek-oh** [jaisidhsingh/CoN-CLIP#2]
Thank you for sharing checkpoints from your wonderful project! 
Could you possibly host them on huggingface hub, github release, or google drive for easier access via shell commands (i.e., wget and gdown)?

**Comment by ytaek-oh** [comment]
I just found a python package to download from OneDrive url, and it works with your checkpoint urls.
https://github.com/loribonna/onedrivedownloader

Closing this issue.
Thanks,

**Comment by jaisidhsingh** [comment]
Hi Youngtaek. I just saw your issue, glad that you could solve it. I'll add the OneDrive downloader to the README to help others. Thank you so much!
